version: '3'

services:

  man-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=man_vw
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306

  man-main:
    image: man
    restart: on-failure
    depends_on:
      - man-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=man-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=man_vw
      - DATABASE_PORT=3306